In [1]:
import pandas as pd
import re
import os
import json

In [2]:
directory = ['Algorithm','Data_structure']

In [3]:
#планируется словарь алгоритмов для более быстрого создания всех датафреймов
alg_dict = {'sort': ['bubble_sort', 'cocktail_sort','comb_sort','counting_sort','gnome_sort','heap_sort',
                     'insertion_sort','merge_sort','quick_sort','radix_sort','selection_sort','---'],
            'find': ['binary_search', 'linear_search', 'quick_select']}

In [4]:
data_arr = ['CyclicNode', 'DoubleLinkedList','DynamicArray','HashTable','SingleLinkedList','AVL_Tree',
            'Binary_Tree','Heap','Queue','Set','Trie']

In [15]:
def natural_sort_key(s):
    return [int(t) if t.isdigit() else t for t in re.split(r'(\d+)', s)]

def remove_chars(string):
    chars_to_remove = '()0123456789 '
    return ''.join(char for char in string if char not in chars_to_remove)

def make_dataset_alg(directory,alg_dict,method):
    df = pd.DataFrame(columns = ['output','input','instruction'])
    for key, values in alg_dict.items():
        for value in values:
            file_path = f'dataset\{directory}\{key}\{value}\{method}'
            file_list = sorted(os.listdir(file_path), key=natural_sort_key)
            for file_name in file_list:
                with open(file_path + '/' + file_name,'r', encoding = 'utf-8') as f:
                    lines = f.readlines()
                file_alg = remove_chars(file_name)
                if file_name[-2:] != ').py':
                    df.loc[len(df)] = [file_alg[:-4] ,'',''.join(lines)]
    return df

def make_dataset_data(directory,data_arr):
    df = pd.DataFrame(columns = ['output','input','instruction'])
    for i in data_arr:
        file_path = f'dataset\{directory}\{i}'
        file_list = sorted(os.listdir(file_path), key=natural_sort_key)
        for file_name in file_list:
            with open(file_path + '/' + file_name,'r', encoding = 'utf-8') as f:
                lines = f.readlines()
            file_data = remove_chars(file_name)
            if file_name[-2:] != ').py':
                df.loc[len(df)] = [file_data[:-4] ,'',''.join(lines)]
    return df

def create_file(name,method = None):
    if method:
        df = make_dataset_alg(directory[0],alg_dict,method)
        df.to_csv(f'csv_for_LLaMa\{name}.csv')
        data = df.to_dict('records')
    
        with open(f'csv_for_LLaMa/{name}.json', 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
    else:
        df = make_dataset_data(directory[1],data_arr)
        df.to_csv(f'csv_for_LLaMa\{name}.csv')
        data = df.to_dict('records')
    
        with open(f'csv_for_LLaMa/{name}.json', 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
    return df

In [6]:
df = make_dataset_alg(directory[0],alg_dict,'train')
df.to_csv('csv_for_LLaMa\data_train (1).csv')
data = df.to_dict('records')

with open('csv_for_LLaMa/data_train (1).json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)
df

           output input                                        instruction
0     bubble_sort        def swap_items(collection, i, j):\n    collect...
1     bubble_sort        def iterative_bubble_sort(data):\n    length =...
2     bubble_sort        def element_exchange_sort(collection):\n    de...
3     bubble_sort        def conditional_swap_bubble_sort(arr):\n    de...
4     bubble_sort        def indexed_bubble_sort(listing):\n    out_idx...
...           ...   ...                                                ...
1445          ---        def delete_node(root, key):\n    if root is No...
1446          ---        Node* deleteNode(Node* root, int key) {\n    i...
1447          ---        Node deleteNode(Node root, int key) {\n    if ...
1448          ---        Одной из ключевых особенностей квантовых вычис...
1449          ---                            import array\nimport typing\n

[1450 rows x 3 columns]

In [7]:
df = create_file('data_train (test)','train')

In [8]:
df

           output input                                        instruction
0     bubble_sort        def swap_items(collection, i, j):\n    collect...
1     bubble_sort        def iterative_bubble_sort(data):\n    length =...
2     bubble_sort        def element_exchange_sort(collection):\n    de...
3     bubble_sort        def conditional_swap_bubble_sort(arr):\n    de...
4     bubble_sort        def indexed_bubble_sort(listing):\n    out_idx...
...           ...   ...                                                ...
1445          ---        def delete_node(root, key):\n    if root is No...
1446          ---        Node* deleteNode(Node* root, int key) {\n    i...
1447          ---        Node deleteNode(Node root, int key) {\n    if ...
1448          ---        Одной из ключевых особенностей квантовых вычис...
1449          ---                            import array\nimport typing\n

[1450 rows x 3 columns]

In [16]:
df = create_file('structures')

In [17]:
df

         output input                                        instruction
0    CyclicNode        from typing import TypeVar, Generic, Optional\...
1    CyclicNode        from typing import TypeVar, Generic, Optional\...
2    CyclicNode        from typing import TypeVar, Generic, Optional\...
3    CyclicNode        from typing import TypeVar, Generic, Optional\...
4    CyclicNode        from typing import TypeVar, Generic, Optional\...
..          ...   ...                                                ...
435        Trie        from dataclasses import dataclass\nfrom typing...
436        Trie        from dataclasses import dataclass\nfrom typing...
437        Trie        from dataclasses import dataclass\nfrom typing...
438        Trie        from dataclasses import dataclass\nfrom typing...
439        Trie        from dataclasses import dataclass\nfrom typing...

[440 rows x 3 columns]