In [33]:
import pandas as pd
import re
import os
import json

In [34]:
directory = ['Algorithm','Data_structure']

In [35]:
#планируется словарь алгоритмов для более быстрого создания всех датафреймов
alg_dict = {'sort': ['bubble_sort', 'quick_sort','selection_sort','merge_sort','insertion_sort'], 'find': ['binary_search', 'linear_search', 'quick_select']}

In [36]:
data_arr = ['CyclicNode', 'DoubleLinkedList','DynamicArray','HashTable','SingleLinkedList']

In [37]:
def natural_sort_key(s):
    return [int(t) if t.isdigit() else t for t in re.split(r'(\d+)', s)]

def remove_chars(string):
    chars_to_remove = '()0123456789'
    return ''.join(char for char in string if char not in chars_to_remove)

def make_dataset_alg(directory,alg_dict):
    df = pd.DataFrame(columns = ['output','input','instruction'])
    for key, values in alg_dict.items():
        for value in values:
            file_path = f'dataset\{directory}\{key}\{value}'
            file_list = sorted(os.listdir(file_path), key=natural_sort_key)
            for file_name in file_list:
                with open(file_path + '/' + file_name,'r', encoding = 'utf-8') as f:
                    lines = f.readlines()
                file_alg = remove_chars(file_name)
                if file_name[-2:] != ').py':
                    df.loc[len(df)] = [file_alg[:-3] ,'',''.join(lines)]
    return df

def make_dataset_data(directory,data_arr):
    df = pd.DataFrame(columns = ['output','input','instruction'])
    for i in data_arr:
        file_path = f'dataset\{directory}\{i}'
        file_list = sorted(os.listdir(file_path), key=natural_sort_key)
        for file_name in file_list:
            with open(file_path + '/' + file_name,'r', encoding = 'utf-8') as f:
                lines = f.readlines()
            file_data = remove_chars(file_name)
            if file_name[-2:] != ').py':
                df.loc[len(df)] = [file_data[:-3] ,'',''.join(lines)]
    return df

In [38]:
df = make_dataset_data(directory[1],data_arr)
df

,output,input,instruction
0,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
1,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
2,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
3,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
4,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
...,...,...,...
195,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
196,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
197,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
198,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
199,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...

In [39]:
df.to_csv('csv_for_LLaMa\data.csv')

In [40]:
data = df.to_dict('records')

with open('csv_for_LLaMa/data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

In [24]:
data = df.to_dict('records')

with open('csv_for_LLaMa/test2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

In [3]:
code.split('def')[1]

" __init__(self, value: K):\n        self.value: K = value\n        self.next_item: Optional['CircularItem[K]'] = None\n        self.prev_item: Optional['CircularItem[K]'] = None\n\n\nclass CircularList(Generic[K]):\n    "

In [23]:
df

,output,input,instruction
0,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
1,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
2,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
3,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
4,CyclicNode,,"from typing import TypeVar, Generic, Optional\..."
...,...,...,...
195,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
196,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
197,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
198,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...
199,SingleLinkedList,,from dataclasses import dataclass\nfrom typing...